name: Slash Test

on:
  issue_comment:
    types: [created]

permissions:
  actions: write
  contents: read

jobs:
  trigger:
    if: github.event.issue.pull_request && contains(github.event.comment.body, '/test')
    runs-on: ubuntu-latest

    steps:
      - uses: actions/github-script@v7
        with:
          script: |
            await github.rest.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: "tests.yml",
              ref: context.payload.issue.pull_request.head.ref
            })
